## Assignment
> ##### *NumPy Problems*
> ##### *Pandas Problems*
> ##### *Matplotlib Problems*

#### *1.1 Basic Array Operations*
Convert the mpg column into a NumPy array and calculate:
> The mean, median, and standard deviation of mpg.

> The number of cars with mpg greater than 25.

In [14]:
import pandas as pd
import numpy as np

df = pd.read_csv('auto-mpg (1).csv')

mpg_ary = np.array(df["mpg"]) 

mean_mpg = np.mean(mpg_ary)
median_mpg = np.median(mpg_ary)
std_mpg = np.std(mpg_ary)

print("Mean mpg:", mean_mpg)
print("Median mpg:", median_mpg)
print("Standard Deviation of mpg:", std_mpg)

Mean mpg: 23.514572864321607
Median mpg: 23.0
Standard Deviation of mpg: 7.806159061274433


In [15]:
mean_mpg = np.mean(mpg_ary)
print("Mean mpg:", mean_mpg)

Mean mpg: 23.514572864321607


In [11]:
mpg_ary

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

#### 1.2 Filtering
Using NumPy, filter all cars with more than 6 cylinders.
Return the corresponding car_name as a list.

In [39]:
mask = df['cylinders'] > 6

cars_over_6_cyl = df.loc[mask, 'car name'].tolist()
cars_over_6_cyl

['chevrolet chevelle malibu',
 'buick skylark 320',
 'plymouth satellite',
 'amc rebel sst',
 'ford torino',
 'ford galaxie 500',
 'chevrolet impala',
 'plymouth fury iii',
 'pontiac catalina',
 'amc ambassador dpl',
 'dodge challenger se',
 "plymouth 'cuda 340",
 'chevrolet monte carlo',
 'buick estate wagon (sw)',
 'ford f250',
 'chevy c20',
 'dodge d200',
 'hi 1200d',
 'chevrolet impala',
 'pontiac catalina brougham',
 'ford galaxie 500',
 'plymouth fury iii',
 'dodge monaco (sw)',
 'ford country squire (sw)',
 'pontiac safari (sw)',
 'chevrolet impala',
 'pontiac catalina',
 'plymouth fury iii',
 'ford galaxie 500',
 'amc ambassador sst',
 'mercury marquis',
 'buick lesabre custom',
 'oldsmobile delta 88 royale',
 'chrysler newport royal',
 'amc matador (sw)',
 'chevrolet chevelle concours (sw)',
 'ford gran torino (sw)',
 'plymouth satellite custom (sw)',
 'buick century 350',
 'amc matador',
 'chevrolet malibu',
 'ford gran torino',
 'dodge coronet custom',
 'mercury marquis brou

#### *1.3 Statistical Analysis*
Compute the 25th, 50th, and 75th percentiles of the weight column using NumPy.

In [45]:
def percentile(data, percent):
    perce=np.percentile(data, percent)
    return perce

weight_ary = np.array(df["weight"]) 


q1 = percentile(weight_ary, 25)
print("Q1:", q1)
q2 = percentile(weight_ary, 50)
print("Q2:", q2)
q3 = percentile(weight_ary, 75)
print("Q3:", q3)

Q1: 2223.75
Q2: 2803.5
Q3: 3608.0


#### *1.4 Array Manipulation*
Convert the acceleration column into a NumPy array and normalize its values
(scale between 0 and 1).

In [50]:
acc_ary = np.array(df["acceleration"]) 


In [ ]:
minacc = np.min(acc_ary)
maxacc = np.max(acc_ary)
acc_normalized = (acc_ary - minacc) / (maxacc - minacc)
acc_normalized

array([0.23809524, 0.20833333, 0.17857143, 0.23809524, 0.14880952,
       0.11904762, 0.05952381, 0.0297619 , 0.11904762, 0.0297619 ,
       0.11904762, 0.        , 0.08928571, 0.11904762, 0.41666667,
       0.44642857, 0.44642857, 0.47619048, 0.38690476, 0.74404762,
       0.56547619, 0.38690476, 0.56547619, 0.26785714, 0.41666667,
       0.35714286, 0.41666667, 0.32738095, 0.625     , 0.38690476,
       0.44642857, 0.35714286, 0.6547619 , 0.29761905, 0.44642857,
       0.44642857, 0.44642857, 0.44642857, 0.23809524, 0.20833333,
       0.32738095, 0.29761905, 0.20833333, 0.23809524, 0.23809524,
       0.32738095, 0.6547619 , 0.41666667, 0.38690476, 0.35714286,
       0.35714286, 0.68452381, 0.38690476, 0.6547619 , 0.5952381 ,
       0.6547619 , 0.74404762, 0.44642857, 0.53571429, 0.92261905,
       0.68452381, 0.50595238, 0.23809524, 0.23809524, 0.32738095,
       0.29761905, 0.20833333, 0.17857143, 0.32738095, 0.32738095,
       0.26785714, 0.32738095, 0.26785714, 0.35714286, 0.47619

#### *1.5 Broadcasting*
Increase all horsepower values by 10% and store the updated values in a new
NumPy array. Handle missing data (if any) by replacing it with the mean of the
column before applying the increase.

In [60]:
hp_ary = pd.to_numeric(df['horsepower'], errors='coerce')

hp_mean = hp_ary.mean()
hp_ary = hp_ary.fillna(hp_mean)

hp_increased = np.array(hp_ary) * 1.1
hp_increased

array([143.        , 181.5       , 165.        , 165.        ,
       154.        , 217.8       , 242.        , 236.5       ,
       247.5       , 209.        , 187.        , 176.        ,
       165.        , 247.5       , 104.5       , 104.5       ,
       106.7       ,  93.5       ,  96.8       ,  50.6       ,
        95.7       ,  99.        , 104.5       , 124.3       ,
        99.        , 236.5       , 220.        , 231.        ,
       212.3       ,  96.8       ,  99.        , 104.5       ,
       114.91632653, 110.        , 115.5       , 110.        ,
        96.8       , 110.        , 181.5       , 192.5       ,
       168.3       , 165.        , 198.        , 187.        ,
       192.5       , 121.        ,  79.2       , 110.        ,
        96.8       ,  94.6       ,  99.        ,  77.        ,
        83.6       ,  71.5       ,  75.9       ,  66.        ,
        77.        , 104.5       ,  88.        ,  59.4       ,
        99.        ,  94.6       , 181.5       , 192.5 

#### *1.6 Boolean Indexing*
Find the average displacement of cars with an origin of 2 (Europe) using NumPy indexing.

In [63]:
europe_mask = df['origin'] == 2

europe_displacement = np.array(df.loc[europe_mask, 'displacement'])

europe_avg_displacement = np.mean(europe_displacement)

print(f"Average displacement of European cars: {europe_avg_displacement}")

Average displacement of European cars: 109.14285714285714


#### *1.7 Matrix Operations*
Create a 2D NumPy array containing the columns mpg, horsepower, and weight.
Compute the dot product of this matrix with a given vector [1, 0.5, -0.2].

In [65]:
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd
data = pd.read_csv("auto-mpg (1).csv")

In [68]:
array = np.array(data[["mpg", "horsepower", "weight"]])

In [69]:
array

array([[18.0, '130', 3504],
       [15.0, '165', 3693],
       [18.0, '150', 3436],
       ...,
       [32.0, '84', 2295],
       [28.0, '79', 2625],
       [31.0, '82', 2720]], shape=(398, 3), dtype=object)

In [83]:
hp_numeric = pd.to_numeric(df['horsepower'], errors='coerce')
hp_mean = hp_numeric.mean()
hp_numeric = hp_numeric.fillna(hp_mean)

matrix = np.array([
    df['mpg'],
    hp_numeric,
    df['weight']
]).T

vector = np.array([1, 0.5, -0.2])

result = np.dot(matrix, vector)
print("Shape of result:", result.shape)
print("First few values of the dot product:")
print(result)

Shape of result: (398,)
First few values of the dot product:
[-617.8        -641.1        -594.2        -595.6        -602.8
 -754.2        -746.8        -740.9        -758.5        -660.
 -612.6        -627.8        -662.2        -490.7        -402.9
 -497.1        -488.3        -453.9        -355.         -318.
 -465.9        -417.         -402.5        -364.3        -463.6
 -805.5        -765.2        -760.4        -840.9        -355.
 -379.8        -373.1        -331.96530612 -457.8        -619.3
 -598.8        -597.4        -589.6        -745.3        -791.3
 -740.3        -730.2        -889.         -851.2        -927.5
 -519.4        -423.6        -587.4        -565.8        -378.
 -351.6        -349.8        -345.         -291.1        -253.1
 -309.8        -330.         -384.1        -360.2        -400.8
 -416.6        -381.2        -759.3        -775.5        -737.
 -735.3        -642.4        -811.6        -809.9        -799.2
 -776.4        -398.5        -688.4        -741.

#### 1.8 Sorting
Use NumPy to sort the cars by model_year in descending order and display the first
five car names.

In [86]:
sorted_indices = np.argsort(df['model year'])[::-1]

top_5_cars = df['car name'].iloc[sorted_indices[:5]].tolist()

print("First five car names sorted by model year (descending):")
for car in top_5_cars:
    print(car)

First five car names sorted by model year (descending):
chevy s-10
ford ranger
dodge rampage
vw pickup
ford mustang gl


#### *9. Correlation*
Compute the Pearson correlation coefficient between mpg and weight using
NumPy.

In [97]:
correlation = np.corrcoef(mpg_ary, weight_ary)[0,1]
print("Pearson correlation coefficient between mpg and weight", correlation)

Pearson correlation coefficient between mpg and weight -0.8317409332443352


#### *10.Conditional Aggregates*
Calculate the mean mpg for cars grouped by the number of cylinders using NumPy
techniques.

In [109]:
unique_cylinders = np.unique(df['cylinders'])

for cyl in unique_cylinders:
    mask = df['cylinders'] == cyl
    mean = np.mean(df[mask]['mpg'])
    print("Mean MPG for:",cyl , "cylinders:", mean)

Mean MPG for: 3 cylinders: 20.55
Mean MPG for: 4 cylinders: 29.28676470588235
Mean MPG for: 5 cylinders: 27.366666666666664
Mean MPG for: 6 cylinders: 19.985714285714284
Mean MPG for: 8 cylinders: 14.963106796116506
